version: '3.3'

services:
  java-maven-app:
    image: ${IMAGE}
    ports: 
      - 8080:8080
  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data